### ISSUE TITLE
[BUG]创建活动接口报错！

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#11]
## 返回错误信息
```
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userid in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>296</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userrole in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>301</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_qq in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>305</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_useraddress in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>309</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_insurance in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>311</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_usercamp in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>318</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_usercamppad in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>320</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_usersleepingbag in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>322</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userinterphone in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>324</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userbag in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>326</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userBurner in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>328</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userpot in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>330</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_comments in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php</b> on line
<b>332</b>
<br />
<br />
<b>Notice</b>:  Undefined index: event_joinlist_userid in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Model/JoinList.php</b> on line
<b>23</b>
<br />
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'Column 'event_joinlist_username' cannot be null' in /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php:246
Stack trace:
#0 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php(323): NotORM_Result-&gt;query('INSERT INTO eve...', Array)
#1 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php(340): NotORM_Result-&gt;insert_multi(Array)
#2 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Model/JoinList.php(27): NotORM_Result-&gt;insert(Array)
#3 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php(339): Model_JoinList-&gt;add(Array)
#4 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Api/Event.php(463): Domain_Event-&gt;addEvent(Array)
#5 [internal function]: Api_Event-&gt;addEvent()
#6 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/PhalApi.php(55): call_user_func(Array)
#7 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Public/index.php(16): PhalApi-&gt;respon in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php</b> on line
<b>246</b>
<br />
```

##输入的POSTMAN参数
```
POST /PhalApi/Public/?service=Event.AddEvent HTTP/1.1
Host: localhost
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: d446105f-8bec-3ef8-906d-61b5596ca4d7

{
"event_comments":"4324",
"event_createUserId":"35",
"event_destination":"tea",
"event_detail":"<p>65456</p>↵",
"event_endtime":"2017-07-21 22:48:00",
"event_gather_location":"23",
"event_gather_time":"2017-07-22 22:48:40",
"event_join_endtime":"2017-08-23 22:48:00",
"event_join_starttime":"2017-07-28 22:48:00",
"event_maxhiker":"12",
"event_name":"testtest",
"event_place_of_departure":"teas",
"event_starttime":"2017-07-20 22:48:00",
"event_type":"正常拉练"
}
```

**Comment by later2015** [comment]
已修复，请重试。
