### ISSUE TITLE
[Bug]修改活动接口返回报错；Event.EditEvent

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#12]
##Event.EditEvent报错信息：

```
<br />
<b>Notice</b>:  Undefined index: event_id in <b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Model/Event.php</b> on line <b>43</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'Unknown column 'eventId' in 'field list'' in /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php:246
Stack trace:
#0 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php(393): NotORM_Result-&gt;query('UPDATE event_in...', Array)
#1 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Model/Event.php(43): NotORM_Result-&gt;update(Array)
#2 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/Event.php(351): Model_Event-&gt;edit(Array)
#3 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Api/Event.php(508): Domain_Event-&gt;editEvent(Array)
#4 [internal function]: Api_Event-&gt;editEvent()
#5 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/PhalApi.php(55): call_user_func(Array)
#6 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Public/index.php(16): PhalApi-&gt;response()
#7 {main}
  thrown in <b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php</b> on line <b>246</b><br />

```

###发送的请求参数
<img width="432" alt="2017-07-22 21 00 47" src="https://user-images.githubusercontent.com/3896617/28491280-f3cc8eb0-6f20-11e7-884d-0f081dab12eb.png">

**Comment by later2015** [comment]
已修复。
