### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#5]
调用获取bbs列表时：
```
POST /PhalApi/Public/?service=BBS.GetBBSList HTTP/1.1
Host: localhost
Content-Type: application/json
{
	"pagesize": 10,
	"page": 1
}
```

  报错：

```
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'Unknown column 'post_deleteFlag' in 'where clause'' in /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php:246
Stack trace:
#0 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php(780): NotORM_Result-&gt;query('SELECT post_id,...', Array)
#1 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php(857): NotORM_Result-&gt;execute()
#2 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Model/BBS.php(11): NotORM_Result-&gt;fetchAll()
#3 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Domain/BBS.php(55): Model_BBS-&gt;getBBSList(0, 10)
#4 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Demo/Api/BBS.php(86): Domain_BBS-&gt;getBBSList(1, 10)
#5 [internal function]: Api_BBS-&gt;getBBSList()
#6 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/PhalApi.php(55): call_user_func(Array)
#7 /Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/Public/index.php(16): PhalApi-&gt;response()
#8 {main}
  th in
<b>/Applications/XAMPP/xamppfiles/sysuhiker/PhalApi/PhalApi/NotORM/NotORM/Result.php</b> on line
<b>246</b>
<br />
```

**Comment by later2015** [comment]
加了个字段，本地数据库执行下sql即可。
ALTER TABLE event_bbs
  ADD 	post_deleteFlag varchar(1) NULL DEFAULT 'N' COMMENT '删除标识，Y-删除，N-未删除'  ;
